[speak]
engine = "flite"
# for available voices: flite -lv
speaker = "slt"

[listen]
engine = "scenario"
scenario = "scenario.txt"
hmm    = "/usr/share/pocketsphinx/model/en-us/en-us"
dict   = "/usr/share/pocketsphinx/model/en-us/cmudict-en-us.dict"
lm     = "/usr/share/pocketsphinx/model/en-us/en-us.lm.bin"
samples = 512
sample_rate = 16000
channels = 1

[think]
dry = false

[see]
engine = "opencv"
model = "models/haarcascade_frontalface_default.xml"
framex = 960
framey = 720
